version: '3'
services:
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/public
    environment:
      VIRTUAL_HOST: ".minck.cl"
      LETSENCRYPT_HOST: ".minck.cl"
      LETSENCRYPT_EMAIL: "@minck.cl"
networks:
  default:
    external:
      name: "wetrust"